// GENERATED by tool/gen_mode_l10n.py — do not edit.
import '../l10n/app_localizations.dart';

/// The app's texts with pet mode applied (#93): a message with a
/// `Neutral` twin answers with the twin when [pets] is on.
class ModeLocalizations implements AppLocalizations {
  final AppLocalizations base;
  final bool pets;

  const ModeLocalizations(this.base, this.pets);

  @override
  String get localeName => base.localeName;

  @override
  String get abortScan => base.abortScan;

  @override
  String get abortScanBody => base.abortScanBody;

  @override
  String get abortScanTitle => base.abortScanTitle;

  @override
  String get about => base.about;

  @override
  String get aboutAndFeedback => base.aboutAndFeedback;

  @override
  String get aboutTagline => pets ? base.aboutTaglineNeutral : base.aboutTagline;

  @override
  String get aboutTaglineNeutral => base.aboutTaglineNeutral;

  @override
  String get addAppointment => base.addAppointment;

  @override
  String get addCat => pets ? base.addCatNeutral : base.addCat;

  @override
  String get addCatNeutral => base.addCatNeutral;

  @override
  String get addFlier => base.addFlier;

  @override
  String get addPhoto => base.addPhoto;

  @override
  String get addPhotosTo => base.addPhotosTo;

  @override
  String get addPositionOption => base.addPositionOption;

  @override
  String get addReminder => base.addReminder;

  @override
  String get addStray => base.addStray;

  @override
  String get addressFormatHint => base.addressFormatHint;

  @override
  String get addressFoundTitle => base.addressFoundTitle;

  @override
  String get addressFromHost => base.addressFromHost;

  @override
  String get addressLocated => base.addressLocated;

  @override
  String get addressNotFound => base.addressNotFound;

  @override
  String get ageLabel => base.ageLabel;

  @override
  String ageMonths(int months) => base.ageMonths(months);

  @override
  String ageYears(int years) => base.ageYears(years);

  @override
  String get agenda => base.agenda;

  @override
  String get agendaEmpty => pets ? base.agendaEmptyNeutral : base.agendaEmpty;

  @override
  String get agendaEmptyNeutral => base.agendaEmptyNeutral;

  @override
  String get alertDayBefore => base.alertDayBefore;

  @override
  String get alertHourBefore => base.alertHourBefore;

  @override
  String get alertLabel => base.alertLabel;

  @override
  String get alertNone => base.alertNone;

  @override
  String get allDayLabel => base.allDayLabel;

  @override
  String get allowAlways => base.allowAlways;

  @override
  String get allowOnce => base.allowOnce;

  @override
  String get alsoBan => base.alsoBan;

  @override
  String get appTitle => base.appTitle;

  @override
  String get applyCrop => base.applyCrop;

  @override
  String get appointmentLabel => base.appointmentLabel;

  @override
  String get appointmentTitleLabel => base.appointmentTitleLabel;

  @override
  String get archiveAction => base.archiveAction;

  @override
  String archiveCandidateLine(String date, String size) => base.archiveCandidateLine(date, size);

  @override
  String archiveConfirmBody(String names) => base.archiveConfirmBody(names);

  @override
  String archiveConfirmTitle(int count) => base.archiveConfirmTitle(count);

  @override
  String archiveDone(int count) => base.archiveDone(count);

  @override
  String get archiveExplainer => pets ? base.archiveExplainerNeutral : base.archiveExplainer;

  @override
  String get archiveExplainerNeutral => base.archiveExplainerNeutral;

  @override
  String archiveFailed(String error) => base.archiveFailed(error);

  @override
  String get archiveNotSaved => base.archiveNotSaved;

  @override
  String archiveSelected(int count) => base.archiveSelected(count);

  @override
  String get archiveTitle => base.archiveTitle;

  @override
  String arrivedFrom(String cat, String place) => base.arrivedFrom(cat, place);

  @override
  String arrivedPlain(String cat) => base.arrivedPlain(cat);

  @override
  String asOfDate(String date) => base.asOfDate(date);

  @override
  String get asOfToday => base.asOfToday;

  @override
  String get authorsSection => base.authorsSection;

  @override
  String get backLabel => base.backLabel;

  @override
  String get bansSection => base.bansSection;

  @override
  String get birthdateInFuture => base.birthdateInFuture;

  @override
  String bornAfterDeceased(String date) => base.bornAfterDeceased(date);

  @override
  String get breedBengal => base.breedBengal;

  @override
  String get breedBritishShorthair => base.breedBritishShorthair;

  @override
  String get breedEuropeanShorthair => base.breedEuropeanShorthair;

  @override
  String get breedMaineCoon => base.breedMaineCoon;

  @override
  String get breedNorwegianForestCat => base.breedNorwegianForestCat;

  @override
  String get breedPersian => base.breedPersian;

  @override
  String get breedRagdoll => base.breedRagdoll;

  @override
  String get breedSiamese => base.breedSiamese;

  @override
  String get breedSphynx => base.breedSphynx;

  @override
  String bundleImportFailed(String error) => base.bundleImportFailed(error);

  @override
  String bundleImported(String result) => base.bundleImported(result);

  @override
  String get bundleNewerError => base.bundleNewerError;

  @override
  String get buyCoffee => base.buyCoffee;

  @override
  String get byMessenger => base.byMessenger;

  @override
  String get byMessengerExplainer => base.byMessengerExplainer;

  @override
  String get calendarGone => base.calendarGone;

  @override
  String get calendarMirrorLabel => base.calendarMirrorLabel;

  @override
  String get calendarMirrorSubtitle => base.calendarMirrorSubtitle;

  @override
  String get calendarNotChosen => base.calendarNotChosen;

  @override
  String get calendarPermissionDenied => base.calendarPermissionDenied;

  @override
  String get calendarRowOff => base.calendarRowOff;

  @override
  String calendarRowOn(String name) => base.calendarRowOn(name);

  @override
  String get cancel => base.cancel;

  @override
  String get captureFlier => base.captureFlier;

  @override
  String get card => base.card;

  @override
  String cardTitle(String name) => base.cardTitle(name);

  @override
  String get catList => pets ? base.catListNeutral : base.catList;

  @override
  String get catListNeutral => base.catListNeutral;

  @override
  String catalogDeleted(String name, String where) => base.catalogDeleted(name, where);

  @override
  String catalogExportFailed(String error) => base.catalogExportFailed(error);

  @override
  String get catalogHolds => base.catalogHolds;

  @override
  String get catalogNameLabel => base.catalogNameLabel;

  @override
  String catalogNameTaken(String name) => base.catalogNameTaken(name);

  @override
  String get catalogsTitle => base.catalogsTitle;

  @override
  String get cats => pets ? base.catsNeutral : base.cats;

  @override
  String catsCount(int count) => pets ? base.catsCountNeutral(count) : base.catsCount(count);

  @override
  String catsCountNeutral(int count) => base.catsCountNeutral(count);

  @override
  String get catsNeutral => base.catsNeutral;

  @override
  String get catsOnAppointment => pets ? base.catsOnAppointmentNeutral : base.catsOnAppointment;

  @override
  String get catsOnAppointmentNeutral => base.catsOnAppointmentNeutral;

  @override
  String get celebrationsSubtitle => pets ? base.celebrationsSubtitleNeutral : base.celebrationsSubtitle;

  @override
  String get celebrationsSubtitleNeutral => base.celebrationsSubtitleNeutral;

  @override
  String get celebrationsToggle => base.celebrationsToggle;

  @override
  String get changeDateLabel => base.changeDateLabel;

  @override
  String changeSince(String delta, String date) => base.changeSince(delta, date);

  @override
  String get chipScanHint => pets ? base.chipScanHintNeutral : base.chipScanHint;

  @override
  String get chipScanHintNeutral => base.chipScanHintNeutral;

  @override
  String get choose => base.choose;

  @override
  String get chooseFromGallery => base.chooseFromGallery;

  @override
  String get chooseWhatToMove => base.chooseWhatToMove;

  @override
  String get clowderLabel => pets ? base.clowderLabelNeutral : base.clowderLabel;

  @override
  String get clowderLabelNeutral => base.clowderLabelNeutral;

  @override
  String get clowders => pets ? base.clowdersNeutral : base.clowders;

  @override
  String get clowdersNeutral => base.clowdersNeutral;

  @override
  String get coffeeSubtitle => base.coffeeSubtitle;

  @override
  String get conflictBody => base.conflictBody;

  @override
  String conflictOn(String field) => base.conflictOn(field);

  @override
  String get connectToWifiFirst => base.connectToWifiFirst;

  @override
  String get copied => base.copied;

  @override
  String get copyCode => base.copyCode;

  @override
  String get crashBody => base.crashBody;

  @override
  String get crashLastRunBody => base.crashLastRunBody;

  @override
  String get crashRestart => base.crashRestart;

  @override
  String get crashSendReport => base.crashSendReport;

  @override
  String get crashTitle => base.crashTitle;

  @override
  String get create => base.create;

  @override
  String get createNewInstead => base.createNewInstead;

  @override
  String get cropAgain => base.cropAgain;

  @override
  String get cropPhoto => base.cropPhoto;

  @override
  String get cropPortrait => base.cropPortrait;

  @override
  String get cropTitle => base.cropTitle;

  @override
  String csvSavedTo(String path) => base.csvSavedTo(path);

  @override
  String get dangerButton => base.dangerButton;

  @override
  String get dangerThanks => base.dangerThanks;

  @override
  String dateFormatError(String format) => base.dateFormatError(format);

  @override
  String get dateInFuture => base.dateInFuture;

  @override
  String deceasedBeforeBirth(String date) => base.deceasedBeforeBirth(date);

  @override
  String get deceasedInFuture => base.deceasedInFuture;

  @override
  String get declineAction => base.declineAction;

  @override
  String get delete => base.delete;

  @override
  String get deleteAppointment => base.deleteAppointment;

  @override
  String deleteAppointmentGroup(int count) => pets ? base.deleteAppointmentGroupNeutral(count) : base.deleteAppointmentGroup(count);

  @override
  String deleteAppointmentGroupNeutral(int count) => base.deleteAppointmentGroupNeutral(count);

  @override
  String get deleteCat => pets ? base.deleteCatNeutral : base.deleteCat;

  @override
  String get deleteCatBody => pets ? base.deleteCatBodyNeutral : base.deleteCatBody;

  @override
  String get deleteCatBodyNeutral => base.deleteCatBodyNeutral;

  @override
  String get deleteCatNeutral => base.deleteCatNeutral;

  @override
  String get deleteCatalog => base.deleteCatalog;

  @override
  String deleteCatalogBody(String name) => pets ? base.deleteCatalogBodyNeutral(name) : base.deleteCatalogBody(name);

  @override
  String deleteCatalogBodyNeutral(String name) => base.deleteCatalogBodyNeutral(name);

  @override
  String get deleteClowder => pets ? base.deleteClowderNeutral : base.deleteClowder;

  @override
  String deleteClowderBody(int count) => pets ? base.deleteClowderBodyNeutral(count) : base.deleteClowderBody(count);

  @override
  String deleteClowderBodyNeutral(int count) => base.deleteClowderBodyNeutral(count);

  @override
  String get deleteClowderEmptyBody => pets ? base.deleteClowderEmptyBodyNeutral : base.deleteClowderEmptyBody;

  @override
  String get deleteClowderEmptyBodyNeutral => base.deleteClowderEmptyBodyNeutral;

  @override
  String get deleteClowderNeutral => base.deleteClowderNeutral;

  @override
  String get deletePhoto => base.deletePhoto;

  @override
  String get deletePhotoBody => base.deletePhotoBody;

  @override
  String get deletePhotoTitle => base.deletePhotoTitle;

  @override
  String deleteQuestion(String name) => base.deleteQuestion(name);

  @override
  String get deletedDone => base.deletedDone;

  @override
  String get dimension => base.dimension;

  @override
  String get dimensionLength => base.dimensionLength;

  @override
  String get dimensionTemperature => base.dimensionTemperature;

  @override
  String get dimensionVolume => base.dimensionVolume;

  @override
  String get dimensionWeight => base.dimensionWeight;

  @override
  String get displayBarcode => base.displayBarcode;

  @override
  String get displayFormat => base.displayFormat;

  @override
  String get displayPlain => base.displayPlain;

  @override
  String get displayQr => base.displayQr;

  @override
  String get doneLabel => base.doneLabel;

  @override
  String get dragOverTheCat => pets ? base.dragOverTheCatNeutral : base.dragOverTheCat;

  @override
  String get dragOverTheCatNeutral => base.dragOverTheCatNeutral;

  @override
  String get dragToSelect => pets ? base.dragToSelectNeutral : base.dragToSelect;

  @override
  String get dragToSelectNeutral => base.dragToSelectNeutral;

  @override
  String get dueDateLabel => base.dueDateLabel;

  @override
  String dueInDays(int count) => base.dueInDays(count);

  @override
  String get dueToday => base.dueToday;

  @override
  String get duplicateMergedIn => base.duplicateMergedIn;

  @override
  String get editLabel => base.editLabel;

  @override
  String get editLabelAppointment => base.editLabelAppointment;

  @override
  String get editOptions => base.editOptions;

  @override
  String get existingCat => pets ? base.existingCatNeutral : base.existingCat;

  @override
  String get existingCatNeutral => base.existingCatNeutral;

  @override
  String get existingClowder => pets ? base.existingClowderNeutral : base.existingClowder;

  @override
  String get existingClowderNeutral => base.existingClowderNeutral;

  @override
  String get exportCsv => base.exportCsv;

  @override
  String get exportIcs => base.exportIcs;

  @override
  String get exportShareFile => base.exportShareFile;

  @override
  String get familySection => base.familySection;

  @override
  String fatherNotMale(String name) => base.fatherNotMale(name);

  @override
  String fieldBackTo(String field, String value) => base.fieldBackTo(field, value);

  @override
  String fieldCleared(String field) => base.fieldCleared(field);

  @override
  String fieldHistoryOf(String field, String name) => base.fieldHistoryOf(field, name);

  @override
  String get fieldType => base.fieldType;

  @override
  String get fields => base.fields;

  @override
  String get findDuplicates => base.findDuplicates;

  @override
  String get finishLabel => base.finishLabel;

  @override
  String get finishUntickHint => pets ? base.finishUntickHintNeutral : base.finishUntickHint;

  @override
  String get finishUntickHintNeutral => base.finishUntickHintNeutral;

  @override
  String get flierLayoutUnknown => base.flierLayoutUnknown;

  @override
  String flierRecognized(String name) => base.flierRecognized(name);

  @override
  String folderSyncFailed(String error) => base.folderSyncFailed(error);

  @override
  String folderSynced(String result) => base.folderSynced(result);

  @override
  String get folderUnreachable => base.folderUnreachable;

  @override
  String get forBoth => base.forBoth;

  @override
  String get forCats => pets ? base.forCatsNeutral : base.forCats;

  @override
  String get forCatsNeutral => base.forCatsNeutral;

  @override
  String get forClowders => pets ? base.forClowdersNeutral : base.forClowders;

  @override
  String get forClowdersNeutral => base.forClowdersNeutral;

  @override
  String get fromVideo => base.fromVideo;

  @override
  String get genderFatherFemale => pets ? base.genderFatherFemaleNeutral : base.genderFatherFemale;

  @override
  String get genderFatherFemaleNeutral => base.genderFatherFemaleNeutral;

  @override
  String get genderMotherMale => pets ? base.genderMotherMaleNeutral : base.genderMotherMale;

  @override
  String get genderMotherMaleNeutral => base.genderMotherMaleNeutral;

  @override
  String get githubIssues => base.githubIssues;

  @override
  String goBackBody(int count) => base.goBackBody(count);

  @override
  String get goBackChanged => base.goBackChanged;

  @override
  String goBackFileFailed(String error) => base.goBackFileFailed(error);

  @override
  String get goBackTitle => base.goBackTitle;

  @override
  String get goBackToHere => base.goBackToHere;

  @override
  String get graphLabel => base.graphLabel;

  @override
  String get hardDeleteAction => base.hardDeleteAction;

  @override
  String hardDeleteWarning(Object name) => base.hardDeleteWarning(name);

  @override
  String get helpAgenda => pets ? base.helpAgendaNeutral : base.helpAgenda;

  @override
  String get helpAgendaNeutral => base.helpAgendaNeutral;

  @override
  String get helpArchive => pets ? base.helpArchiveNeutral : base.helpArchive;

  @override
  String get helpArchiveNeutral => base.helpArchiveNeutral;

  @override
  String get helpCard => pets ? base.helpCardNeutral : base.helpCard;

  @override
  String get helpCardNeutral => base.helpCardNeutral;

  @override
  String get helpCat => pets ? base.helpCatNeutral : base.helpCat;

  @override
  String get helpCatNeutral => base.helpCatNeutral;

  @override
  String get helpCatalogs => pets ? base.helpCatalogsNeutral : base.helpCatalogs;

  @override
  String get helpCatalogsNeutral => base.helpCatalogsNeutral;

  @override
  String get helpClowder => pets ? base.helpClowderNeutral : base.helpClowder;

  @override
  String get helpClowderNeutral => base.helpClowderNeutral;

  @override
  String get helpDuplicates => pets ? base.helpDuplicatesNeutral : base.helpDuplicates;

  @override
  String get helpDuplicatesNeutral => base.helpDuplicatesNeutral;

  @override
  String get helpFields => pets ? base.helpFieldsNeutral : base.helpFields;

  @override
  String get helpFieldsNeutral => base.helpFieldsNeutral;

  @override
  String get helpFlier => pets ? base.helpFlierNeutral : base.helpFlier;

  @override
  String get helpFlierNeutral => base.helpFlierNeutral;

  @override
  String get helpGoBack => base.helpGoBack;

  @override
  String get helpHome => pets ? base.helpHomeNeutral : base.helpHome;

  @override
  String get helpHomeNeutral => base.helpHomeNeutral;

  @override
  String get helpMap => pets ? base.helpMapNeutral : base.helpMap;

  @override
  String get helpMapNeutral => base.helpMapNeutral;

  @override
  String get helpMatches => pets ? base.helpMatchesNeutral : base.helpMatches;

  @override
  String get helpMatchesNeutral => base.helpMatchesNeutral;

  @override
  String get helpStrays => pets ? base.helpStraysNeutral : base.helpStrays;

  @override
  String get helpStraysNeutral => base.helpStraysNeutral;

  @override
  String get helpSync => base.helpSync;

  @override
  String get helpTimeline => base.helpTimeline;

  @override
  String get helpTitle => base.helpTitle;

  @override
  String get hideLabel => base.hideLabel;

  @override
  String get host => base.host;

  @override
  String get hostExplainer => base.hostExplainer;

  @override
  String get hostWithoutWifi => base.hostWithoutWifi;

  @override
  String get hostedLink => base.hostedLink;

  @override
  String get hotspotAndroidOnly => base.hotspotAndroidOnly;

  @override
  String get hotspotHint => base.hotspotHint;

  @override
  String get hotspotJoinNote => base.hotspotJoinNote;

  @override
  String icsSavedTo(String path) => base.icsSavedTo(path);

  @override
  String get importBundle => base.importBundle;

  @override
  String get importLabel => base.importLabel;

  @override
  String get importShareTitle => pets ? base.importShareTitleNeutral : base.importShareTitle;

  @override
  String get importShareTitleNeutral => base.importShareTitleNeutral;

  @override
  String get includePrivate => base.includePrivate;

  @override
  String get inlineQr => base.inlineQr;

  @override
  String get inlineTooBig => base.inlineTooBig;

  @override
  String get intoCatalog => base.intoCatalog;

  @override
  String get introBody1 => pets ? base.introBody1Neutral : base.introBody1;

  @override
  String get introBody1Neutral => base.introBody1Neutral;

  @override
  String get introBody2 => base.introBody2;

  @override
  String get introBody3 => base.introBody3;

  @override
  String get introBody4 => pets ? base.introBody4Neutral : base.introBody4;

  @override
  String get introBody4Neutral => base.introBody4Neutral;

  @override
  String get introDone => base.introDone;

  @override
  String get introNext => base.introNext;

  @override
  String get introReplayTitle => base.introReplayTitle;

  @override
  String get introSkip => base.introSkip;

  @override
  String get introTitle1 => pets ? base.introTitle1Neutral : base.introTitle1;

  @override
  String get introTitle1Neutral => base.introTitle1Neutral;

  @override
  String get introTitle2 => base.introTitle2;

  @override
  String get introTitle3 => base.introTitle3;

  @override
  String get introTitle4 => pets ? base.introTitle4Neutral : base.introTitle4;

  @override
  String get introTitle4Neutral => base.introTitle4Neutral;

  @override
  String get invalidCode => base.invalidCode;

  @override
  String get iosLocalNetworkHint => base.iosLocalNetworkHint;

  @override
  String get join => base.join;

  @override
  String get keepDeleted => base.keepDeleted;

  @override
  String get keepScanning => base.keepScanning;

  @override
  String get keepThisFrame => base.keepThisFrame;

  @override
  String get kindCat => pets ? base.kindCatNeutral : base.kindCat;

  @override
  String get kindCatNeutral => base.kindCatNeutral;

  @override
  String get kindClowder => pets ? base.kindClowderNeutral : base.kindClowder;

  @override
  String get kindClowderNeutral => base.kindClowderNeutral;

  @override
  String get kindField => base.kindField;

  @override
  String get kittensLabel => pets ? base.kittensLabelNeutral : base.kittensLabel;

  @override
  String get kittensLabelNeutral => base.kittensLabelNeutral;

  @override
  String get labelName => base.labelName;

  @override
  String get labelPhoto => base.labelPhoto;

  @override
  String get labelProfileImage => base.labelProfileImage;

  @override
  String get language => base.language;

  @override
  String lastBackupFailed(String error) => base.lastBackupFailed(error);

  @override
  String lastSyncWith(String peer, String time) => base.lastSyncWith(peer, time);

  @override
  String get latitudeLongitude => base.latitudeLongitude;

  @override
  String get leftStray => base.leftStray;

  @override
  String leftTo(String cat, String place) => base.leftTo(cat, place);

  @override
  String get linkFieldLabel => base.linkFieldLabel;

  @override
  String get littermatesLabel => base.littermatesLabel;

  @override
  String get locateAddress => base.locateAddress;

  @override
  String get locationDenied => base.locationDenied;

  @override
  String get locationDeniedForever => base.locationDeniedForever;

  @override
  String get locationNoFix => base.locationNoFix;

  @override
  String get locationServiceOff => base.locationServiceOff;

  @override
  String get lookUpId => base.lookUpId;

  @override
  String lookupFailed(String url) => base.lookupFailed(url);

  @override
  String lookupUrlHelp(String token) => base.lookupUrlHelp(token);

  @override
  String get lookupUrlLabel => base.lookupUrlLabel;

  @override
  String get machineTranslated => base.machineTranslated;

  @override
  String get malePregnant => pets ? base.malePregnantNeutral : base.malePregnant;

  @override
  String get malePregnantNeutral => base.malePregnantNeutral;

  @override
  String get manageCatalogs => base.manageCatalogs;

  @override
  String get map => base.map;

  @override
  String get mapSearchHint => pets ? base.mapSearchHintNeutral : base.mapSearchHint;

  @override
  String get mapSearchHintNeutral => base.mapSearchHintNeutral;

  @override
  String get markDone => base.markDone;

  @override
  String get markPhoto => base.markPhoto;

  @override
  String get markPrivate => base.markPrivate;

  @override
  String get markTitle => pets ? base.markTitleNeutral : base.markTitle;

  @override
  String get markTitleNeutral => base.markTitleNeutral;

  @override
  String get matchCandidatesTitle => base.matchCandidatesTitle;

  @override
  String get merge => base.merge;

  @override
  String mergeBody(String name) => base.mergeBody(name);

  @override
  String get mergeInto => base.mergeInto;

  @override
  String mergeIntoQuestion(String name) => base.mergeIntoQuestion(name);

  @override
  String mergeThisInto(String kind) => base.mergeThisInto(kind);

  @override
  String metersApart(String distance) => base.metersApart(distance);

  @override
  String get missingSinceLabel => base.missingSinceLabel;

  @override
  String get modeCats => base.modeCats;

  @override
  String get modePets => base.modePets;

  @override
  String get moderationSubtitle => base.moderationSubtitle;

  @override
  String get moderationTitle => base.moderationTitle;

  @override
  String get momentArchive => base.momentArchive;

  @override
  String get momentHardDelete => base.momentHardDelete;

  @override
  String get momentImport => base.momentImport;

  @override
  String get momentManual => base.momentManual;

  @override
  String get momentMerge => base.momentMerge;

  @override
  String get momentSync => base.momentSync;

  @override
  String motherNotFemale(String name) => base.motherNotFemale(name);

  @override
  String moveIntoNewCatalog(String name) => base.moveIntoNewCatalog(name);

  @override
  String get moveTo => base.moveTo;

  @override
  String get moveToCatalog => base.moveToCatalog;

  @override
  String movedTo(String name) => base.movedTo(name);

  @override
  String movedToCatalog(int count, String name) => base.movedToCatalog(count, name);

  @override
  String get name => base.name;

  @override
  String get nameThisMoment => base.nameThisMoment;

  @override
  String get newCat => pets ? base.newCatNeutral : base.newCat;

  @override
  String get newCatNeutral => base.newCatNeutral;

  @override
  String get newCatalog => base.newCatalog;

  @override
  String get newClowder => pets ? base.newClowderNeutral : base.newClowder;

  @override
  String get newClowderNeutral => base.newClowderNeutral;

  @override
  String get newField => base.newField;

  @override
  String get newStray => base.newStray;

  @override
  String get nextPin => base.nextPin;

  @override
  String get noCatsHint => pets ? base.noCatsHintNeutral : base.noCatsHint;

  @override
  String get noCatsHintNeutral => base.noCatsHintNeutral;

  @override
  String get noClowderStrayOption => pets ? base.noClowderStrayOptionNeutral : base.noClowderStrayOption;

  @override
  String get noClowderStrayOptionNeutral => base.noClowderStrayOptionNeutral;

  @override
  String get noClowdersYet => pets ? base.noClowdersYetNeutral : base.noClowdersYet;

  @override
  String get noClowdersYetNeutral => base.noClowdersYetNeutral;

  @override
  String get noDuplicates => base.noDuplicates;

  @override
  String get noFaceYet => base.noFaceYet;

  @override
  String get noFolderChosenYet => base.noFolderChosenYet;

  @override
  String get noIdInLink => base.noIdInLink;

  @override
  String get noLinkedField => base.noLinkedField;

  @override
  String get noLocationAvailable => base.noLocationAvailable;

  @override
  String get noMatchCandidates => base.noMatchCandidates;

  @override
  String get noMissingCats => pets ? base.noMissingCatsNeutral : base.noMissingCats;

  @override
  String get noMissingCatsNeutral => base.noMissingCatsNeutral;

  @override
  String noOtherToMergeInto(String kind) => base.noOtherToMergeInto(kind);

  @override
  String get noPlacesFound => base.noPlacesFound;

  @override
  String get noRegistryLinks => base.noRegistryLinks;

  @override
  String get noRepeatLabel => base.noRepeatLabel;

  @override
  String get noStraysRightNow => base.noStraysRightNow;

  @override
  String get noWritableCalendar => base.noWritableCalendar;

  @override
  String get notACatlogFile => base.notACatlogFile;

  @override
  String get notAShareCode => base.notAShareCode;

  @override
  String get notSaved => base.notSaved;

  @override
  String get notesLabel => base.notesLabel;

  @override
  String get nothingNewInBundle => base.nothingNewInBundle;

  @override
  String get nothingToArchive => base.nothingToArchive;

  @override
  String get ocrUnavailable => base.ocrUnavailable;

  @override
  String get ok => base.ok;

  @override
  String get onMapLabel => base.onMapLabel;

  @override
  String get open => base.open;

  @override
  String get openSettings => base.openSettings;

  @override
  String get openSourceLicenses => base.openSourceLicenses;

  @override
  String get optionsOnePerLine => base.optionsOnePerLine;

  @override
  String get orTypeCode => base.orTypeCode;

  @override
  String get otherOption => base.otherOption;

  @override
  String get outcomeTitle => base.outcomeTitle;

  @override
  String overdueByDays(int count) => base.overdueByDays(count);

  @override
  String overwritesValue(String value) => base.overwritesValue(value);

  @override
  String get ownValue => base.ownValue;

  @override
  String ownerOfCat(String name) => base.ownerOfCat(name);

  @override
  String parentBornAfterKitten(String name, String date) => pets ? base.parentBornAfterKittenNeutral(name, date) : base.parentBornAfterKitten(name, date);

  @override
  String parentBornAfterKittenNeutral(String name, String date) => base.parentBornAfterKittenNeutral(name, date);

  @override
  String get phoneLabel => base.phoneLabel;

  @override
  String get photos => base.photos;

  @override
  String photosAddedTo(String count, String name) => base.photosAddedTo(count, name);

  @override
  String get pickCalendar => base.pickCalendar;

  @override
  String get pickCatsTitle => pets ? base.pickCatsTitleNeutral : base.pickCatsTitle;

  @override
  String get pickCatsTitleNeutral => base.pickCatsTitleNeutral;

  @override
  String get pickFramesTitle => base.pickFramesTitle;

  @override
  String get pickOnMap => base.pickOnMap;

  @override
  String get pin => base.pin;

  @override
  String pinLabel(String pin) => base.pinLabel(pin);

  @override
  String get planChooserAppointment => base.planChooserAppointment;

  @override
  String get planChooserReminder => base.planChooserReminder;

  @override
  String get planChooserTitle => base.planChooserTitle;

  @override
  String get plannedSection => base.plannedSection;

  @override
  String get prevPin => base.prevPin;

  @override
  String get print => base.print;

  @override
  String get privateLabel => base.privateLabel;

  @override
  String get proposeAnotherName => base.proposeAnotherName;

  @override
  String qrFailed(String error) => base.qrFailed(error);

  @override
  String get qrFoundHint => base.qrFoundHint;

  @override
  String get qrNone => base.qrNone;

  @override
  String quietForYears(int years) => base.quietForYears(years);

  @override
  String get rangeAll => base.rangeAll;

  @override
  String get rangeCustom => base.rangeCustom;

  @override
  String get rangeMonth => base.rangeMonth;

  @override
  String get rangeWeek => base.rangeWeek;

  @override
  String get rangeYear => base.rangeYear;

  @override
  String get readOnlyCalendar => base.readOnlyCalendar;

  @override
  String get recordSightingHere => base.recordSightingHere;

  @override
  String get rememberService => base.rememberService;

  @override
  String get rememberServiceHint => base.rememberServiceHint;

  @override
  String get reminderDialogHint => base.reminderDialogHint;

  @override
  String get reminderField => base.reminderField;

  @override
  String get reminderFor => base.reminderFor;

  @override
  String get reminderLabel => base.reminderLabel;

  @override
  String get removeReminderLabel => base.removeReminderLabel;

  @override
  String get removeTrust => base.removeTrust;

  @override
  String get rename => base.rename;

  @override
  String get renameCat => pets ? base.renameCatNeutral : base.renameCat;

  @override
  String get renameCatNeutral => base.renameCatNeutral;

  @override
  String get renameClowder => pets ? base.renameClowderNeutral : base.renameClowder;

  @override
  String get renameClowderNeutral => base.renameClowderNeutral;

  @override
  String get renameField => base.renameField;

  @override
  String get repeatTitle => base.repeatTitle;

  @override
  String get replaceAddressOption => base.replaceAddressOption;

  @override
  String get reportProblemOrIdea => base.reportProblemOrIdea;

  @override
  String get resolve => base.resolve;

  @override
  String get restoreAction => base.restoreAction;

  @override
  String restoreDeletedBody(String names) => base.restoreDeletedBody(names);

  @override
  String restoreDeletedTitle(int count) => base.restoreDeletedTitle(count);

  @override
  String get resyncCalendar => base.resyncCalendar;

  @override
  String get revertSubtitle => base.revertSubtitle;

  @override
  String get revertThisChange => base.revertThisChange;

  @override
  String sameIdField(String field) => base.sameIdField(field);

  @override
  String get save => base.save;

  @override
  String get savingLabel => base.savingLabel;

  @override
  String get scanCode => base.scanCode;

  @override
  String get scanPrintedCode => base.scanPrintedCode;

  @override
  String get scanShareLabel => base.scanShareLabel;

  @override
  String get scrubFrames => base.scrubFrames;

  @override
  String get searchByNameHint => pets ? base.searchByNameHintNeutral : base.searchByNameHint;

  @override
  String get searchByNameHintNeutral => base.searchByNameHintNeutral;

  @override
  String get searchCats => pets ? base.searchCatsNeutral : base.searchCats;

  @override
  String get searchCatsNeutral => base.searchCatsNeutral;

  @override
  String get searchNoResults => pets ? base.searchNoResultsNeutral : base.searchNoResults;

  @override
  String get searchNoResultsNeutral => base.searchNoResultsNeutral;

  @override
  String get searchPlaceHint => base.searchPlaceHint;

  @override
  String get seenHereNow => base.seenHereNow;

  @override
  String get selectClowderHint => pets ? base.selectClowderHintNeutral : base.selectClowderHint;

  @override
  String get selectClowderHintNeutral => base.selectClowderHintNeutral;

  @override
  String sessionsSoFar(int count) => base.sessionsSoFar(count);

  @override
  String get setAsProfileImage => base.setAsProfileImage;

  @override
  String get settings => base.settings;

  @override
  String get shareAsImage => base.shareAsImage;

  @override
  String get shareAsPdf => base.shareAsPdf;

  @override
  String get shareBundle => base.shareBundle;

  @override
  String shareFileFailed(String error) => base.shareFileFailed(error);

  @override
  String get sharePublicly => base.sharePublicly;

  @override
  String shareSource(String url) => base.shareSource(url);

  @override
  String get shareWhitelistExplainer => base.shareWhitelistExplainer;

  @override
  String sharedCatalogIs(String name) => base.sharedCatalogIs(name);

  @override
  String get sharedFolder => base.sharedFolder;

  @override
  String get sharedFolderExplainer => base.sharedFolderExplainer;

  @override
  String get showHiddenLabel => base.showHiddenLabel;

  @override
  String get showOlderMoments => base.showOlderMoments;

  @override
  String get showOnMap => base.showOnMap;

  @override
  String get showTipsAgain => base.showTipsAgain;

  @override
  String get siblingsLabel => base.siblingsLabel;

  @override
  String get sightingRecorded => base.sightingRecorded;

  @override
  String get similarName => base.similarName;

  @override
  String get sortLabel => base.sortLabel;

  @override
  String get sourceCode => base.sourceCode;

  @override
  String get spotAddReminderCat => pets ? base.spotAddReminderCatNeutral : base.spotAddReminderCat;

  @override
  String get spotAddReminderCatNeutral => base.spotAddReminderCatNeutral;

  @override
  String get spotAddReminderClowder => pets ? base.spotAddReminderClowderNeutral : base.spotAddReminderClowder;

  @override
  String get spotAddReminderClowderNeutral => base.spotAddReminderClowderNeutral;

  @override
  String get spotAgendaAdd => base.spotAgendaAdd;

  @override
  String get spotAgendaCalendar => base.spotAgendaCalendar;

  @override
  String get spotCardChips => base.spotCardChips;

  @override
  String get spotCatEdit => pets ? base.spotCatEditNeutral : base.spotCatEdit;

  @override
  String get spotCatEditNeutral => base.spotCatEditNeutral;

  @override
  String get spotCatMenu => pets ? base.spotCatMenuNeutral : base.spotCatMenu;

  @override
  String get spotCatMenuNeutral => base.spotCatMenuNeutral;

  @override
  String get spotDone => base.spotDone;

  @override
  String get spotEar => base.spotEar;

  @override
  String get spotHomeAgenda => base.spotHomeAgenda;

  @override
  String get spotHomeCatalog => base.spotHomeCatalog;

  @override
  String get spotHomeMenu => base.spotHomeMenu;

  @override
  String get spotHomeStrays => pets ? base.spotHomeStraysNeutral : base.spotHomeStrays;

  @override
  String get spotHomeStraysNeutral => base.spotHomeStraysNeutral;

  @override
  String get spotHomeSync => base.spotHomeSync;

  @override
  String get spotMapLayers => pets ? base.spotMapLayersNeutral : base.spotMapLayers;

  @override
  String get spotMapLayersNeutral => base.spotMapLayersNeutral;

  @override
  String get spotMapSearch => pets ? base.spotMapSearchNeutral : base.spotMapSearch;

  @override
  String get spotMapSearchNeutral => base.spotMapSearchNeutral;

  @override
  String get spotReplayDone => base.spotReplayDone;

  @override
  String get spotReplaySubtitle => base.spotReplaySubtitle;

  @override
  String get spotReplayTitle => base.spotReplayTitle;

  @override
  String get spotStraysFlier => pets ? base.spotStraysFlierNeutral : base.spotStraysFlier;

  @override
  String get spotStraysFlierNeutral => base.spotStraysFlierNeutral;

  @override
  String get spotStraysScan => pets ? base.spotStraysScanNeutral : base.spotStraysScan;

  @override
  String get spotStraysScanNeutral => base.spotStraysScanNeutral;

  @override
  String get start => base.start;

  @override
  String get startHosting => base.startHosting;

  @override
  String get starterAddress => base.starterAddress;

  @override
  String get starterBirthdate => base.starterBirthdate;

  @override
  String get starterBreed => base.starterBreed;

  @override
  String get starterChipId => base.starterChipId;

  @override
  String get starterColor => base.starterColor;

  @override
  String get starterDeceased => base.starterDeceased;

  @override
  String get starterEmail => base.starterEmail;

  @override
  String get starterFather => base.starterFather;

  @override
  String get starterGender => base.starterGender;

  @override
  String get starterMother => base.starterMother;

  @override
  String get starterNeutered => base.starterNeutered;

  @override
  String get starterPhone => base.starterPhone;

  @override
  String get starterPosition => base.starterPosition;

  @override
  String get starterPregnant => base.starterPregnant;

  @override
  String get starterRemarks => base.starterRemarks;

  @override
  String get starterResponsible => base.starterResponsible;

  @override
  String get starterSpecies => base.starterSpecies;

  @override
  String get starterStatus => base.starterStatus;

  @override
  String get starterWeight => base.starterWeight;

  @override
  String get statusBarn => base.statusBarn;

  @override
  String get statusClinic => base.statusClinic;

  @override
  String get statusForeverHome => base.statusForeverHome;

  @override
  String get statusFoster => base.statusFoster;

  @override
  String get statusOwner => base.statusOwner;

  @override
  String get statusShelter => base.statusShelter;

  @override
  String get stepCat => pets ? base.stepCatNeutral : base.stepCat;

  @override
  String get stepCatNeutral => base.stepCatNeutral;

  @override
  String get stepFace => base.stepFace;

  @override
  String get stepFaceHint => pets ? base.stepFaceHintNeutral : base.stepFaceHint;

  @override
  String get stepFaceHintNeutral => base.stepFaceHintNeutral;

  @override
  String get stepFlierText => base.stepFlierText;

  @override
  String get stepOwner => base.stepOwner;

  @override
  String get stepOwnerHint => pets ? base.stepOwnerHintNeutral : base.stepOwnerHint;

  @override
  String get stepOwnerHintNeutral => base.stepOwnerHintNeutral;

  @override
  String get stepRegistry => base.stepRegistry;

  @override
  String get stepRegistryHint => pets ? base.stepRegistryHintNeutral : base.stepRegistryHint;

  @override
  String get stepRegistryHintNeutral => base.stepRegistryHintNeutral;

  @override
  String get stepReview => base.stepReview;

  @override
  String get stopHosting => base.stopHosting;

  @override
  String get stopShowingHidden => base.stopShowingHidden;

  @override
  String storageLine(String db, String photos, int count) => base.storageLine(db, photos, count);

  @override
  String get stray => base.stray;

  @override
  String get strayAreaLabel => base.strayAreaLabel;

  @override
  String get strayCam => base.strayCam;

  @override
  String get strayNoClowder => pets ? base.strayNoClowderNeutral : base.strayNoClowder;

  @override
  String get strayNoClowderNeutral => base.strayNoClowderNeutral;

  @override
  String get strays => base.strays;

  @override
  String get suggestedFrames => base.suggestedFrames;

  @override
  String get summaryAdopted => base.summaryAdopted;

  @override
  String get summaryConflicts => base.summaryConflicts;

  @override
  String get summaryDeceased => base.summaryDeceased;

  @override
  String get summaryEscaped => base.summaryEscaped;

  @override
  String get summaryNew => base.summaryNew;

  @override
  String summaryOther(Object n) => base.summaryOther(n);

  @override
  String get switchBeforeDeleting => base.switchBeforeDeleting;

  @override
  String get sync => base.sync;

  @override
  String get syncChooserInPerson => base.syncChooserInPerson;

  @override
  String get syncChooserInPersonSub => base.syncChooserInPersonSub;

  @override
  String get syncChooserMessenger => base.syncChooserMessenger;

  @override
  String get syncChooserMessengerSub => base.syncChooserMessengerSub;

  @override
  String get syncChooserRemote => base.syncChooserRemote;

  @override
  String get syncChooserRemoteSub => base.syncChooserRemoteSub;

  @override
  String get syncDeclined => base.syncDeclined;

  @override
  String syncFailed(String error) => base.syncFailed(error);

  @override
  String get syncFolderNow => base.syncFolderNow;

  @override
  String get syncNow => base.syncNow;

  @override
  String get syncPeerNewer => base.syncPeerNewer;

  @override
  String get syncPeerNoTls => base.syncPeerNoTls;

  @override
  String get syncPeerOlder => base.syncPeerOlder;

  @override
  String get syncSummaryTitle => base.syncSummaryTitle;

  @override
  String get syncUnreachable => base.syncUnreachable;

  @override
  String get syncWrongHost => base.syncWrongHost;

  @override
  String syncedResult(String result) => base.syncedResult(result);

  @override
  String get systemDefault => base.systemDefault;

  @override
  String get takePhoto => base.takePhoto;

  @override
  String get targetContact => base.targetContact;

  @override
  String get targetDrop => base.targetDrop;

  @override
  String get targetLostPlace => base.targetLostPlace;

  @override
  String get targetRegistryNumber => base.targetRegistryNumber;

  @override
  String get thisIsProfileImage => base.thisIsProfileImage;

  @override
  String get timeLabel => base.timeLabel;

  @override
  String get timeline => base.timeline;

  @override
  String timelineOf(String name) => base.timelineOf(name);

  @override
  String toastAdopted(Object cat, Object home) => base.toastAdopted(cat, home);

  @override
  String toastBorn(Object cat) => pets ? base.toastBornNeutral(cat) : base.toastBorn(cat);

  @override
  String toastBornNeutral(Object cat) => base.toastBornNeutral(cat);

  @override
  String toastDeceased(Object cat) => base.toastDeceased(cat);

  @override
  String toastEscaped(Object cat) => base.toastEscaped(cat);

  @override
  String get toastKindAdoptions => base.toastKindAdoptions;

  @override
  String get toastKindBirths => base.toastKindBirths;

  @override
  String get toastKindDeaths => base.toastKindDeaths;

  @override
  String get toastKindEscapes => base.toastKindEscapes;

  @override
  String get toastKindMoves => base.toastKindMoves;

  @override
  String toastMoved(Object cat, Object home) => base.toastMoved(cat, home);

  @override
  String get toastSettingsSubtitle => base.toastSettingsSubtitle;

  @override
  String get toastSettingsTitle => base.toastSettingsTitle;

  @override
  String trailOf(String name, int count) => base.trailOf(name, count);

  @override
  String get trustBothWaysNote => base.trustBothWaysNote;

  @override
  String trustQuestion(Object author, Object device) => base.trustQuestion(author, device);

  @override
  String get trustedDevicesSection => base.trustedDevicesSection;

  @override
  String typeTheName(String name) => base.typeTheName(name);

  @override
  String typeToConfirm(Object name) => base.typeToConfirm(name);

  @override
  String get typeUnitValue => base.typeUnitValue;

  @override
  String get unbanAction => base.unbanAction;

  @override
  String undoImportBody(int count) => base.undoImportBody(count);

  @override
  String get undoThisImport => base.undoThisImport;

  @override
  String undoneImport(String where) => base.undoneImport(where);

  @override
  String get unhideLabel => base.unhideLabel;

  @override
  String get unitDays => base.unitDays;

  @override
  String get unitMonths => base.unitMonths;

  @override
  String get unitWeeks => base.unitWeeks;

  @override
  String get unitYears => base.unitYears;

  @override
  String get unitsAuto => base.unitsAuto;

  @override
  String get unitsImperial => base.unitsImperial;

  @override
  String get unitsLabel => base.unitsLabel;

  @override
  String get unitsMetric => base.unitsMetric;

  @override
  String get unknownServiceHint => base.unknownServiceHint;

  @override
  String get unmarkPrivate => base.unmarkPrivate;

  @override
  String get unnamed => base.unnamed;

  @override
  String get useCode => base.useCode;

  @override
  String get useFullPhoto => base.useFullPhoto;

  @override
  String get useMyLocation => base.useMyLocation;

  @override
  String get usedOn => base.usedOn;

  @override
  String get value => base.value;

  @override
  String get valueBird => base.valueBird;

  @override
  String get valueCat => base.valueCat;

  @override
  String get valueDog => base.valueDog;

  @override
  String get valueFemale => base.valueFemale;

  @override
  String get valueFerret => base.valueFerret;

  @override
  String get valueGuineaPig => base.valueGuineaPig;

  @override
  String get valueHamster => base.valueHamster;

  @override
  String get valueHorse => base.valueHorse;

  @override
  String get valueMale => base.valueMale;

  @override
  String get valueMixed => base.valueMixed;

  @override
  String get valueNo => base.valueNo;

  @override
  String get valueRabbit => base.valueRabbit;

  @override
  String get valueTortoise => base.valueTortoise;

  @override
  String get valueUnknown => base.valueUnknown;

  @override
  String get valueYes => base.valueYes;

  @override
  String versionLabel(String version, String build) => base.versionLabel(version, build);

  @override
  String get videoMobileOnly => base.videoMobileOnly;

  @override
  String get viewAsList => base.viewAsList;

  @override
  String get viewAsTable => base.viewAsTable;

  @override
  String get viewAsTiles => base.viewAsTiles;

  @override
  String get welcomeBody => base.welcomeBody;

  @override
  String get welcomeTitle => base.welcomeTitle;

  @override
  String get whichNumber => base.whichNumber;

  @override
  String get writeTheDeveloper => base.writeTheDeveloper;

  @override
  String get yourName => base.yourName;

}
