#!/usr/bin/env python3
"""Generates lib/src/mode_l10n.dart: a mode-aware facade over the
generated AppLocalizations. In pet mode every message that has a
`<key>Neutral` twin answers with the twin; everything else forwards.
Run after `flutter gen-l10n` whenever ARB keys change."""
import re
src = open('lib/l10n/app_localizations.dart').read()
body = src[src.index('abstract class AppLocalizations {'):]
members = []
for m in re.finditer(r'^  String get (\w+);$', body, re.M):
    members.append((m.group(1), None))
for m in re.finditer(r'^  String (\w+)\(([^)]*)\);$', body, re.M):
    members.append((m.group(1), m.group(2)))
names = {n for n, _ in members}
out = ['// GENERATED by tool/gen_mode_l10n.py — do not edit.',
       "import '../l10n/app_localizations.dart';", '',
       '/// The app\'s texts with pet mode applied (#93): a message with a',
       '/// `Neutral` twin answers with the twin when [pets] is on.',
       'class ModeLocalizations implements AppLocalizations {',
       '  final AppLocalizations base;', '  final bool pets;', '',
       '  const ModeLocalizations(this.base, this.pets);', '',
       '  @override', '  String get localeName => base.localeName;', '']
for name, params in sorted(members):
    twin = name + 'Neutral'
    if params is None:
        call = lambda n: f'base.{n}'
    else:
        args = ', '.join(p.strip().split()[-1] for p in params.split(',') if p.strip())
        call = lambda n, a=args: f'base.{n}({a})'
    sig = f'String get {name}' if params is None else f'String {name}({params})'
    expr = f'pets ? {call(twin)} : {call(name)}' if twin in names else call(name)
    out += ['  @override', f'  {sig} => {expr};', '']
out.append('}')
open('lib/src/mode_l10n.dart', 'w').write('\n'.join(out) + '\n')
print(f'{len(members)} members, {sum(1 for n,_ in members if n + "Neutral" in names)} twins')
