/// Writes the fixture corpus the desktop core is tested against.
///
///     dart run tool/gen_fixtures.dart ../../desktop/fixtures
///
/// For every scenario: a writer catalog with a fixed device id, key and
/// clock fills itself, publishes into a shared folder and a bundle; two
/// fresh readers import folder and bundle and must agree; their state is
/// the `expected.json` the desktop core has to reproduce.
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:archive/archive_io.dart';
import 'package:catalog_core/catalog_core.dart';
import 'package:sqlite3/sqlite3.dart';

import 'fixtures/dump.dart';
import 'fixtures/folder_copy.dart';
import 'fixtures/scenarios.dart';

/// Fixed key seeds: the writer and the two readers of every scenario.
final _seeds = {
  'writer': List<int>.generate(32, (i) => 1 + i),
  'folderReader': List<int>.generate(32, (i) => 101 + i),
  'bundleReader': List<int>.generate(32, (i) => 201 + i),
};

/// A clock that starts at a fixed moment and moves one second per read.
DateTime _tick = DateTime.utc(2026, 1, 1, 10);
DateTime _clock() => _tick = _tick.add(const Duration(seconds: 1));

/// A catalog with a known device id and signing key: the settings the
/// store would make at random are written before it opens.
CatalogStore _catalog(Directory dir, String role, String author) {
  final seed = Uint8List.fromList(_seeds[role]!);
  final key = SigningKey.fromSeed(seed);
  final path = '${dir.path}/catalog.db';
  final db = sqlite3.open(path);
  db.execute('CREATE TABLE IF NOT EXISTS local_settings '
      '(key TEXT PRIMARY KEY, value TEXT NOT NULL)');
  db.execute(
      'INSERT INTO local_settings (key, value) VALUES (?, ?), (?, ?), (?, ?)', [
    'device',
    deviceIdFromKey(key.publicKey),
    'signseed',
    key.seedHex,
    'signsince',
    '1',
  ]);
  db.dispose();
  return CatalogStore.open(path)..author = author;
}

Future<void> main(List<String> args) async {
  if (args.length != 1) {
    stderr.writeln('usage: dart run tool/gen_fixtures.dart <fixtures dir>');
    exit(2);
  }
  useSystemSqlite();
  CatalogStore.clock = _clock;
  final root = Directory(args[0])..createSync(recursive: true);
  final index = StringBuffer('# Fixture corpus\n\n'
      'Generated by `packages/catalog_core/tool/gen_fixtures.dart` from the '
      'Dart core; the desktop core imports every scenario and must dump '
      'the same `expected.json`. Do not edit by hand.\n\n');
  for (final scenario in scenarios) {
    _tick = DateTime.utc(2026, 1, 1, 10);
    final out = Directory('${root.path}/${scenario.name}');
    if (out.existsSync()) out.deleteSync(recursive: true);
    out.createSync(recursive: true);
    final work = Directory.systemTemp.createTempSync('catlog_fixture_');
    try {
      final writer = _catalog(
          Directory('${work.path}/writer')..createSync(), 'writer', 'Ada');
      scenario.build(writer);
      final folderDir = Directory('${out.path}/folder')..createSync();
      await folderSync(writer, folderDir.path);
      final bundlePath = '${out.path}/bundle.catsync';
      writeBundle(writer, bundlePath);
      _applyTamper(scenario, writer, folderDir, bundlePath);
      _fixZipTimes(bundlePath);

      final folderReader = _catalog(
          Directory('${work.path}/folder-reader')..createSync(),
          'folderReader',
          'Reader');
      final folderResult =
          await folderSyncIn(folderReader, memoryCopy(folderDir));
      final viaFolder = dumpState(folderReader);

      final bundleReader = _catalog(
          Directory('${work.path}/bundle-reader')..createSync(),
          'bundleReader',
          'Reader');
      final bundleResult = importBundle(bundleReader, bundlePath);
      final viaBundle = dumpState(bundleReader);

      final folderJson = _json(viaFolder);
      if (folderJson != _json(viaBundle)) {
        File('${out.path}/expected-bundle.json')
            .writeAsStringSync(_json(viaBundle));
        stderr.writeln('${scenario.name}: folder and bundle readers disagree');
        exit(1);
      }
      File('${out.path}/expected.json').writeAsStringSync(_json({
        ...viaFolder,
        'report': reportJson(folderResult.report),
        'bundleReport': reportJson(bundleResult.report),
      }));
      File('${out.path}/scenario.json').writeAsStringSync(_json({
        'name': scenario.name,
        'about': scenario.about,
        'writer': writer.deviceId,
        'writerEntries':
            writer.entriesSince(const {}, includePrivate: true).length,
      }));
      writer.close();
      folderReader.close();
      bundleReader.close();
      index.writeln('- `${scenario.name}`: ${scenario.about}');
      stdout
          .writeln('${scenario.name}: ${viaFolder['entries'].length} entries, '
              '${viaFolder['blobs'].length} photos');
    } finally {
      work.deleteSync(recursive: true);
    }
  }
  File('${root.path}/README.md').writeAsStringSync(index.toString());
}

String _json(Object value) =>
    '${const JsonEncoder.withIndent('  ').convert(value)}\n';

/// Runs the scenario's tamper step over the written folder and bundle.
void _applyTamper(Scenario scenario, CatalogStore writer, Directory folderDir,
    String bundlePath) {
  final tamper = scenario.tamper;
  if (tamper == null) return;
  final root = '${folderDir.path}/catlog-sync';
  final ownFile = File('$root/${writer.deviceId}.jsonl');
  List<Map<String, dynamic>> decode(String text) => [
        for (final line in const LineSplitter().convert(text))
          if (line.trim().isNotEmpty)
            (jsonDecode(line) as Map).cast<String, dynamic>()
      ];
  final archive = ZipDecoder().decodeBytes(File(bundlePath).readAsBytesSync());
  final entriesFile =
      archive.files.firstWhere((f) => f.name.startsWith('entries'));
  final t = Tamper(writer.deviceId, decode(ownFile.readAsStringSync()),
      decode(utf8.decode(entriesFile.content as List<int>)));
  tamper(t);
  ownFile.writeAsStringSync(t.folderLines.map(jsonEncode).join('\n'));
  final ownKeys = [
    if (t.sinceOverride case final since?)
      KeyRecord.make(writer.signingKey, writer.deviceId, since)
    else
      writer.ownKeyRecord
  ];
  File('$root/keys/${writer.deviceId}.json')
      .writeAsStringSync(jsonEncode([for (final k in ownKeys) k.toJson()]));
  for (final MapEntry(key: name, value: records) in t.extraKeyFiles.entries) {
    File('$root/keys/$name')
        .writeAsStringSync(jsonEncode([for (final k in records) k.toJson()]));
  }
  _rewriteZip(bundlePath, (name, bytes) {
    if (name.startsWith('entries')) {
      return utf8.encode(t.bundleLines.map(jsonEncode).join('\n'));
    }
    if (name == keysFile) {
      return utf8.encode(jsonEncode([
        for (final k in [...ownKeys, ...t.extraBundleKeys]) k.toJson()
      ]));
    }
    return bytes;
  });
}

/// Rewrites a zip with every file stamped at the same fixed time: the
/// bundle writer stamps the wall clock, which would change the bytes on
/// every run without changing the bundle.
void _fixZipTimes(String path) => _rewriteZip(path, (_, bytes) => bytes);

void _rewriteZip(
    String path, List<int> Function(String name, List<int> bytes) edit) {
  final archive = ZipDecoder().decodeBytes(File(path).readAsBytesSync());
  final fixed = Archive();
  for (final f in archive.files) {
    final bytes = edit(f.name, f.content as List<int>);
    final copy = ArchiveFile(f.name, bytes.length, bytes)
      ..compress = f.compress
      ..lastModTime = 0;
    fixed.addFile(copy);
  }
  final bytes = ZipEncoder().encode(fixed);
  File(path).writeAsBytesSync(bytes!);
}
